#!/bin/sh

#
# This script sends an HTML-formatted email to approximately 370 people.
#
# These are people who attended the first (ageing) debate in the Sheldonian
# Theatre last year.
#
# When sending HTML email, it is necessary to prepend some MIME headers.
#

spam()
{
	VICTIM=$1
	echo "spamming $VICTIM"
	rm -f tempfile
	echo "To: $VICTIM" > tempfile
	cat mime_header.txt debate_description.html >> tempfile
	/usr/lib/sendmail -t < tempfile
	sleep 1
}

# spam joe.loughry@stx.ox.ac.uk
# spam joe.loughry@applied-math.org
# spam avijitguharoy@gmail.com

# exit 1

spam methionine57@gmail.com
spam joe.loughry@stx.ox.ac.uk
spam adam.fellows@seh.ox.ac.uk
spam wen.ong@wadh.ox.ac.uk
spam craig.slater@magd.ox.ac.uk
spam samantha.binding@worc.ox.ac.uk
spam shermin.goh@exeter.ox.ac.uk
spam tanuj.sapra@chem.ox.ac.uk
spam xumengyun198907@gmail.com
spam robert.simion@chem.ox.ac.uk
spam camstaquinn@gmail.com
spam eamonn.reading@gmail.com
spam qin.lu@chem.ac.ox.uk
spam peixun.li@chem.ox.ac.uk
spam nicholas.chhabra@some.ox.ac.uk
spam emma.stuart@hertford.ox.ac.uk
spam benjamin.dive@trinity.ox.ac.uk
spam theresa.schlagheck@univ.ox.ac.uk
spam aguharoy@gmail.com
spam Maria.Gavriliouk@btinternet.com
spam PeterGKClark@gmail.com
spam alicelynch85@gmail.com
spam david@cathcart.cx
spam martin.evans@eng.ox.ac.uk
spam jp_brown@inbox.com
spam marielle_minere@hotmail.com
spam nathan.jenko@trinity.ox.ac.uk
spam gabriel.rosser@dtc.ox.ac.uk
spam gemcgow@gmail.com
spam alexis.muirwatt@worc.ox.ac.uk
spam JamesStephenLittle@gmail.com
spam isobel.steer@st-hildas.ox.ac.uk
spam marc.zentar@worc.ox.ac.uk
spam ben.hoskin@lmh.ox.ac.uk
spam Fischerj@usa.net
spam carly.wheeler@brookes.ac.uk
spam johannes.schmidt@ludwig.ox.ac.uk
spam laurie.pycroft@balliol.ox.ac.uk
spam cpbrown@gmail.com
spam james.phillips@exeter.ox.ac.uk
spam pasharp@brookes.ac.uk
spam armin.thalhammer@chem.ox.ac.uk
spam lcrilly@brookes.ac.uk
spam yiu.suen@sociology.ox.ac.uk
spam nposford@parkinsons.org.uk
spam mhilbrant@brookes.ac.uk
spam a.robson1@physics.ox.ac.uk
spam rfwondrak@brookes.ac.uk
spam lois.aspinall@wolfson.ox.ac.uk
spam qiuli.zhang@ctsu.ox.ac.uk
spam hrapson@gmail.com
spam maja.kecman@gmail.com
spam oss@andrewsteele.co.uk
spam michael.coward@keble.ox.ac.uk
spam daniel.perez@lincoln.ox.ac.uk
spam vladislava.chalei@stx.ox.ac.uk
spam tom.fuller@gmail.com
spam jack.ross@bnc.ox.ac.uk
spam arvind.singhal@bnc.ox.ac.uk
spam saras.mane@st-annes.ox.ac.uk
spam caroline.phelps@stcatz.ox.ac.uk
spam yanyan.liu@exeter.ox.ac.uk
spam tiago@stats.ox.ac.uk
spam andrei-sorin.ilie@univ.ox.ac.uk
spam mallydenny@gmail.com
spam andrew.douglas@gtc.ox.ac.uk
spam taniahasan@exeter.ox.ac.uk
spam rafal.wiewiora@pmb.ox.ac.uk
spam james.bennett@oriel.ox.ac.uk
spam calum.brown@univ.ox.ac.uk
spam alexander.ogilvie@pmb.ox.ac.uk
spam jonny60@live.co.uk
spam cosmo.grant@merton.ox.ac.uk
spam Harriet.ball@gtc.ox.ac.uk
spam kergon@maths.ox.ac.uk
spam andrea.flack@zoo.ox.ac.uk
spam asger.jakobsen@bnc.ox.ac.uk
spam grte0785@ox.ac.uk
spam marchee88@gmail.com
spam peter.fiske@arch.ox.ac.uk
spam lena.lee@sjc.ox.ac.uk
spam OUSS.to.uansari@neverbox.com
spam OUSS.to.uansari@neverbox.com
spam sofia.piltz@linacre.ox.ac.uk
spam ben.gazzard@stcatz.ox.ac.uk
spam carina.brehony@zoo.ox.ac.uk
spam mohsin.khan@wadh.ox.ac.uk
spam benjamin.hopkins@merton.ox.ac.uk
spam thomas.koller@ccc.ox.ac.uk
spam emily.wendt@magd.ox.ac.uk
spam roland.ivanyi-nagy@ndm.ox.ac.uk
spam chloe.simpson@spc.ox.ac.uk
spam tsz.so@st-hildas.ox.ac.uk
spam cevans6@hotmail.com
spam sjbright@brookes.ac.uk
spam oliver.venn@queens.ox.ac.uk
spam keith.moyse@bioch.ox.ac.uk
spam luke.freman-mills@gmail.com
spam cwolf@astro.ox.ac.uk
spam Phil_Renforth@hotmail.com
spam marih@fmrib.ox.ac.uk
spam eduff@fmrib.ox.ac.uk
spam niels.martens@ccc.ox.ac.uk
spam andrew.dillon@merton.ox.ac.uk
spam sena.yardley@linacre.ox.ac.uk
spam huihui.song@materials.ox.ac.uk
spam jennifer.cable@trinity.ox.ac.uk
spam simon23blake@yahoo.co.uk
spam andrew.elliot@spc.ox.ac.uk
spam jonas.schluter@dtc.ox.ac.uk
spam yiminwumse@gmail.com
spam ziqian.ding@materials.ox.ac.uk
spam nadia_@me.com
spam g.sharman@manchester.ac.uk
spam pierre.vila@trinity.ox.ac.uk
spam tim.kruger@oxfordmartin.ox.ac.uk
spam MARIANNe.debrito@st-hughs.ox.ac.uk
spam anna.watts@st-hughs.ox.ac.uk
spam davidchantawei@gmail.com
spam eloise.aston@gmail.com
spam khalil.davis@merton.ox.ac.uk
spam roger.norum@anthro.ox.ac.uk
spam david.ding@univ.ox.ac.uk
spam maria.muller@bfriars.ox.ac.uk
spam julia.dahlkamp@kellogg.ox.ac.uk
spam chaventietze@gmail.com
spam martin.lukacisin@chch.ox.ac.uk
spam mahnoor.naeem@keble.ox.ac.uk
spam shiori.shakuto-neoh@sant.ox.ac.uk
spam adam.gilbertson@anthro.ox.ac.uk
spam daniel.r.guinness@gmail.com
spam katherine.flynn@sant.ox.ac.uk
spam jonny.gowing@hotmail.com
spam katie.hsih@linacre.ox.ac.uk
spam oliver.zeldin@gmail.com
spam fiona.mcmurray@wolfson.ox.ac.uk
spam hannah.sleven@bioch.ox.ac.ukox.a
spam martin.lottner@gmail.com
spam martin.lottner@gmail.com
spam anca.farcas@sjc.ox.ac.uk
spam penelope.mason@bioch.ox.ac.uk
spam lejla.zubcevic@wolfson.ox.ac.uk
spam hayley.lees@hertford.ox.ac.uk
spam rainer@strubi.ox.ac.uk
spam ela_kuzma@yahoo.de
spam gerryshep@gmail.com
spam lea.carrott@wolfson.ox.ac.uk
spam katerina.douka@rlaha.ox.ac.uk
spam Thomas.gligoris@bioch.ox.ac.uk
spam ben.yu@spc.ox.ac.uk
spam ashley.nord@balliol.ox.ac.uk
spam leanne.slater@bioch.ox.ac.uk
spam leannerichardnz@yahoo.co.uk
spam tara.thean@worc.ox.ac.uk
spam alona.cramer@merton.ox.ac.uk
spam simon.haenni@bioch.ox.ac.uk
spam youxin.kong@merton.ox.ac.uk
spam Cornelia.roibu@some.ox.ac.uk
spam graeme.ball@bioch.ox.ac.uk
spam susan.yu@linacre.ox.ac.uk
spam kirsty.mackay@keble.ox.ac.uk
spam maria.sobczyk@linacre.ox.ac.uk
spam michael84p@web.de
spam linhao.fang@earth.ox.ac.uk
spam dosion1986@gmail.com
spam evelyn.chan@hertford.ox.ac.uk
spam verena.heise@merton.ox.ac.uk
spam anita.jassi@admin.ox.ac.uk
spam heather.house@admin.ox.ac.uk
spam michael.youdell@bioch.ox.ac.uk
spam apnesterova@gmail.com
spam apnesterova@gmail.com
spam ben.zealley@sens.org
spam clarab@earth.ox.ac.uk
spam mary.kroll@ceu.ox.ac.uk
spam tony.richmond@tiscali.co.uk
spam lyn.richmond@tiscali.co.uk
spam atc12@mole.bio.cam.ac.uk
spam iain.inkster@sens.org
spam sophie.robin@st-annes.ox.ac.uk
spam raphael.chow@univ.ox.ac.uk
spam anz.teagle@gmail.com
spam daniel.lage@sjc.ox.ac.uk
spam adam_fellows@hotmail.com
spam mike.gorley@materials.ox.ac.uk
spam laurahares1983@hotmail.com
spam sofia.hauck@st-hughs.ox.ac.uk
spam peter.rush@balliol.ox.ac.uk
spam william.gee@st-annes.ox.ac.uk
spam osasha.fertal@lmh.ox.ac.uk
spam ventsislav.chonev@oriel.ox.ac.uk
spam wuboshen@gmail.com
spam jane.duncan@live.co.uk
spam peter.nelson@new.ox.ac.uk
spam wenye.zhao@new.ox.ac.uk
spam maciej.malinowski@magd.ox.ac.uk
spam rowland.goodbody@st-annes.ox.ac.uk
spam kamila.hussien@oncology.ox.ac.uk
spam tom.graham@new.ox.ac.uk
spam nicky.andrews@lincoln.ox.ac.uk
spam naomi.scott-mearns@stcatz.ox.ac.uk
spam robertsjlr@gmail.com
spam chen.huang@spc.ox.ac.uk
spam jessamy.lowe@new.ox.ac.uk
spam dawn.hollis@balliol.ox.ac.uk
spam alexandre.erler@philosophy.ox.ac.uk
spam ignas.rubikas@stcatz.ox.ac.uk
spam minh.tran@spc.ox.ac.uk
spam amy.smith@merton.ox.ac.uk
spam nicholas.fulton@spc.ox.ac.uk
spam zack.hall@ccc.ox.ac.uk
spam matthew.jones@mansfield.ox.ac.uk
spam joseph.caruana@astro.ox.ac.uk
spam melissa.odonoghue@st-annes.ox.ac.uk
spam vikram.chandra@balliol.ox.ac.uk
spam Sheena.loeffel@seh.ox.ac.uk
spam daryl.ho@balliol.ox.ac.uk
spam william.coleman@balliol.oc.ac.uk
spam adrian.stfrancis@stcatz.ox.ac.uk
spam hannah.long@exeter.ox.ac.uk
spam petra.koulia@merton.ox.ac.uk
spam roman.duda@merton.ox.ac.uk
spam martin.bell@chem.ox.ac.uk
spam arne.bruyneel@merton.ox.ac.uk
spam elin.mccormack@chem.ox.ac.uk
spam vuko_andric@yahoo.de
spam peter.o.koelle@gmail.com
spam 09067128@brookes.ac.uk
spam joram.vanrheede@univ.ox.ac.uk
spam lauren.kutler@lmh.ox.ac.uk
spam shameq@hotmail.com
spam nikolaos.kaplis@magd.ox.ac.uk
spam michael.kendall@new.ox.ac.uk
spam tom.hills@sjc.ox.ac.uk
spam julian.few@trinity.ox.ac.uk
spam ali.naghieh@spi.ox.ac.uk
spam marianne.talbot@conted.ox.ac.uk
spam kevin.reilly@sbs.ox.ac.uk
spam g.djordjevic@oxfordbrookes.net
spam ben_stamp12@hotmail.com
spam leon.musolff.1993@googlemail.com
spam david.owen@keble.ox.ac.uk
spam matthew.ball@new.ox.ac.uk
spam hannah.phillips@univ.ox.ac.uk
spam samuel.whitehead@pmb.ox.ac.uk
spam alexander.moss@kcl.ac.uk
spam claire.sexton@ndcn.ox.ac.uk
spam mquasem1@binghamton.edu
spam martin.rush@magd.oxon.org
spam ejtidy@gmail.com
spam claire.ward@mansfield.ox.ac.uk
spam ashleyrreilly@gmail.com
spam joao.jorge@eng.ox.ac.uk
spam anna.turskaya@mansfield.ox.ac.uk
spam katharine.dusenbury@exeter.ox.ac.uk
spam marie.desaintvictor@pemb.ox.ac.uk
spam richardthe3rd.carino@gmail.com
spam z.verzosa@gmail.com
spam nicole.bernardo@gmail.com
spam jack.nicholas@bnc.ox.ac.uk
spam rachel.evered@hmc.ox.ac.uk
spam y.a.a.van.damme@hum.leidenuniv.nl
spam thomas.mortimer@some.ox.ac.uk
spam irina.bystron@dpag.ox.ac.uk
spam monday98@Verizon.net
spam naren.srinivasan@gmail.com
spam jonniebarton@btinternet.com
spam ivan.dimov@ccc.ox.ac.uk
spam jhjmilne@ucalgary.ca
spam eachan.johnson@new.ox.ac.uk
spam p.upton@open.ac.uk
spam dishue@hotmail.com
spam kate.milne@st-hughs.ox.ac.uk
spam michelle.hutchinson@exeter.ox.ac.uk
spam arwel.pritchard@gmail.com
spam sverre.myhra@materials.ox.ac.uk
spam helen.bergen@psych.ox.ac.uk
spam busby.michael@gmail.com
spam annekathrin.meiburg@lincoln.ox.ac.uk
spam david.wilkins@seh.ox.ac.uk
spam israelfefer@yahoo.com
spam andrew.paverd@balliol.ox.ac.uk
spam gtkysor@gmail.com
spam tasha.tian@gmail.com
spam Caroline.godfrey@dpag.ox.ac.uk
spam yatesc@maths.ox.ac.uk
spam phill.putter@eng.ox.ac.uk
spam olivia.baddeley@balliol.ox.ac.uk
spam santiago@manrique.de
spam gary.whitlock@ctsu.ox.ac.uk
spam wmdturner@hotmail.com
spam fumiko.esashi@path.ox.ac.uk
spam Beth.watts@linacre.ox.ac.uk
spam jack.kennedy@some.ox.ac.uk
spam maria.masher@gmail.com
spam zwartvogeltje@hotmail.com
spam Frankmcamilleri@aol.com
spam johnnybeale@gmail.com
spam emma.james@stcatz.ox.ac.uk
spam joe.grimwade@btinternet.com
spam henrywhittaker3@yahoo.com
spam benjamin.krishna@ccc.ox.ac.uk
spam c.lamm@btinternet.com
spam will.anscombe@lincoln.ox.ac.uk
spam elizabeth.anscombe@magd.ox.ac.uk
spam edward.anderton@oriel.ox.ac.uk
spam nicholas.hasle@magd.ox.ac.uk
spam toby.call@magd.ox.ac.uk
spam arehughserious@gmail.com
spam hcagnan@gmail.com
spam seema.jain@seh.ox.ac.uk
spam Karolina.Chocian@trinity.ox.ac.uk
spam joanna.tung@univ.ox.ac.uk
spam olga.liska@path.ox.ac.uk
spam emmacallander@gmail.com
spam charlie.jarrett-wilkins@univ.ox.ac.uk
spam diana.sofronieva@st-hildas.ox.ac.uk
spam lawrence.hill-cawthorne@law.ox.ac.uk
spam t.hainz@t-online.de
spam claudia.couto@bioch.ox.ac.uk
spam jennifer.juillardmaniece@bnc.ox.ac.uk
spam J.Somogyi@ella.hu
spam georgios.hatzopoulos@bioch.ox.ac.uk
spam antonio.espert@bioch.ox.ac.uk
spam victoria.furio@uv.es
spam steptogap@hotmail.de
spam blackwell.alex@btinternet.com
spam benehalb@students.uni-mainz.de
spam matthew.reynolds@stcatz.ox.ac.uk
spam aakash.dos@gmail.com
spam giulia.mizzon@gmail.com
spam henry.luckhoo@trinity.ox.ac.uk
spam mark.firth@seh.ox.ac.uk
spam stephanie.jaczniakowska-mcgirr@hertford.ox.ac.uk
spam jack.sheppard@worc.ox.ac.uk
spam agnieszka.swiejkowska@pharm.ox.ac.uk
spam daniel.swiejkowski@pharm.ox.ac.uk
spam simao.laranjeira@eng.ox.ac.uk
spam alice.redfern@worc.ox.ac.uk
spam jethrojohnson@gmail.com
spam ryanmacdonald22951@hotmail.co.uk
spam doron.hickey@gmail.com
spam louise.thompson@st-hughs.ox.ac.uk
spam alexandra.walker@linacre.ox.ac.uk
spam elizabeth.german@univ.ox.ac.uk
spam caroline.harrold@hertford.ox.ac.uk
spam hannah.walters@hertford.ox.ac.uk
spam Arnab@tifr.res.in
spam anderson.ryan@oncology.ox.ac.uk
spam jcoffey@brookes.ac.uk
spam prjewitt@aol.com
spam raushan-muhamedz@mail.ru
spam jamie.graham@st-hughs.ox.ac.uk
spam Karl.Austin-Muttitt@st-hughs.ox.ac.uk
spam alexander.deng@sjc.ox.ac.uk
spam john.connell@wolfson.ox.ac.uk
spam spooon@btinternet.com
spam philippa.kraftl@admin.ox.ac.uk
spam brianandrews55@hotmail.com
spam ananya.jaidev@new.ox.ac.uk
spam srinivasa.raghotham@gmail.com
spam naomi.petela@bioch.ox.ac.uk
spam peter.bradshaw@st-hildas.ox.ac.uk
spam GSCARTI@GMAIL.COM
spam joanna.pennack@oriel.ox.ac.uk
spam lynne.cox@bioch.ox.ac.uk
spam davidkchambers@hotmail.com
spam scoles@ucla.edu

echo "Done."

